### ISSUE TITLE
Issue granting access to some repos

### ISSUE THREAD

**Issue by gin0115** [Automattic/team51-cli#177] opened 2022-12-15 12:41 UTC
Had an issue this morning getting access to the JeffGoThelf, took 3 runs to get access to production. 

Just tried again to get access to Om.co and again hitting the same problem, on some instances I can grant myself access (as expected), but in others it just errors out.

Ran in `--dev` mode and grabbed the actual error. It seems the `colaborators\ batch_permission` endpoint is returning a 502

![image](https://user-images.githubusercontent.com/28779094/207861041-70626932-3ec2-4f3a-bab5-e7915934319d.png)

Out of the 4 instances relating to Om.co, I have only been able to get access to 2 of them, no matter how many times I rerun the command. 

Spoke to @ahegyes 

*************
Can confirm this was run while logged into 1Password
OS - Pop!_OS 22.04 LTS x86_64

**Comment by gin0115** [comment] 2022-12-15 12:42
![image](https://user-images.githubusercontent.com/28779094/207861949-9a40eb8a-732c-4783-a58f-7f403c565a0b.png)

**Comment by gin0115** [comment] 2022-12-15 14:35
Appears the error was as a result of the repo being owned by the partner and contractors can not be added via Team51, only the Partner.

See https://a8c.slack.com/archives/C018UMRUN3V/p1671108386937929

Closing this issue as not really an issue. 

Sorry for wasting anyones time

**Comment by ahegyes** [comment] 2022-12-19 09:56
Even so @gin0115, we can probably enhance the error message to be more descriptive of what the issue is. I'm reopening this issue and assigning myself to it with the following scope:

* Add more debug-level messages for methods doing API calls (also helpful for issues like #161);
* Better error parsing ([the Pressable API was hitting many 502 errors](p1671118158868839-slack-C018UMRUN3V) on that day and apparently we're not handling those correctly)

Work on internal tools is paused until January, so that's most likely when this will commence :)

**Comment by gin0115** [comment] 2022-12-19 10:12
Awesome, as always let me know if you want me to test anything from Linux land :)

**Comment by ahegyes** [comment] 2023-05-10 09:59
Closing this issue since the PR for better error handling has been merged.

**Closed as completed by ahegyes** 2023-05-10 09:59 UTC
